# Abilites: When you attack the boss, a random skill will be used, configute it individually
# Possible sounds https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# Possible effects https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html

#Dont touch the location from here, do it manually by commands.

location: 

name: "Warzone Boss"
health: 1200
damage_multiplier: 2

automatic_start: true
cooldown_in_minutes: 1440
remove_star_drop_from_boss: true
remove_wither_skeleton_drops_on_warzone: true

abilities:
  lightning:
    chance: 0.3
    super_lightning: true
    msg_to_player: "&cWarzone Boss: &7You cant against my power"
    #commands:
    #- maybe a espetacular command?
  dodge:
    chance: 1.0
    msg_to_player: "&cWarzone Boss: &7You failed, you are worth nothing"
    block_damage: true
    sounds:
    - ITEM_SHIELD_BLOCK
  impulse:
    chance: 0.3
    msg_to_player: "&cWarzone Boss: &7Agggggrhh"
    knockback_power: 3
    damage_player: 10
    sounds:
    - ENTITY_WITHER_SHOOT
    - ENTITY_PLAYER_ATTACK_SWEEP
  vexing:
    chance: 0.3
    msg_to_player: "&cWarzone Boss: &7Attack my minions"
    effects:
    - BLINDNESS:60:0
    - SLOWNESS:60:0
    sounds:
    - ENTITY_WITHER_SHOOT
    vexing:
      enabled: true
      amount: 3
      radio: 10
  skeletons:
    chance: 0.3
    msg_to_player: "&cWarzone Boss: &7Attack skeletons!"
    effects:
    - SLOWNESS:60:0
    sounds:
    - ENTITY_WITHER_SHOOT
    skeletons:
      enabled: true
      amount: 3
      radio: 10
  explosion:
    chance: 0.3
    msg_to_player: "&cWarzone Boss: &7Dieeeeee!!"  
    create_explosion: true
    sounds:
    - ENTITY_WITHER_SHOOT
    - ENTITY_WITHER_HURT
    - ENTITY_WITHER_SHOOT
    - ENTITY_WITHER_DEATH
    - ENTITY_WITHER_BREAK_BLOCK
    - ENTITY_WITHER_AMBIENT
  custom1: # Why not create your own ability?
    # You can add any config type here only chance is required 
    chance: 0.0
    msg_to_player: "&cWarzone Boss: &7Custom message"  
    commands:
    - eco add %player% 1
    - give %player% arrow 1
    #-any awesome command
    sounds:
    - ENTITY_ENDER_DRAGON_GROWL
    block_damage: true
    knockback_power: 3
    damage_player: 10
    create_explosion: true
    super_lightning: true
    vexing:
      enabled: true
      amount: 3
      radio: 10
    skeletons:
      enabled: true
      amount: 3
      radio: 10
    effects:
     - NAUSEA:60:0

rewards:
  1:
    chance: 1.0
    broadcast_text: ""
    drops: 
    - BONE
    commands: 
    - eco give %player% 100
    - give %player% diamond 4
  2:
    chance: 0.50
    broadcast_text: ""
    drops: 
    - BONE
    commands: 
    - eco give %player% 100
    - give %player% emerald 4
  3:
    chance: 0.0
    broadcast_text: "Example: 0%"
    drops: 
    - DIAMOND 

custom_drops:
  '1737159193811':
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 4189
      type: BOW
    chance: 0.5
    broadcast_text: 'Something special has been dropped'