main: com.ar.askgaming.warzone.WarzonePlugin
name: Warzone
api-version: 1.21
version: 1.8.1
author: AMONLY
softdepend: [PlaceholderAPI]
commands:
  warzone:
    description: Manage warzone mode in your server.
    permission: warzone.commands
    permission-message: You do not have permission to use this command.